apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicasCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailableCount }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalRpcPort }}
          env:
            - name: USERS_RPCADDR
              value: 0.0.0.0:{{ .Values.service.internalRpcPort }}
            - name: USERS_ACCOUNTSRPCADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: accountsRpcAddr
            - name: DBURI
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: dbUri
            - name: MQURI
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: mqUri
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: secret
            - name: RECOVERYSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: recoverySecret
            - name: CENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: centSecret
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: sentryDsn
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}
        - name: secrets
          secret:
            secretName: {{ .Release.Name }}